version: "1"
rules:
  - base: swiftwasm
    upstream: master
    mergeMethod: merge
  - base: master
    upstream: apple:master
    mergeMethod: hardreset
label: ":arrow_heading_down: Upstream Tracking"
